### ISSUE TITLE
0.89 Xiaomi IR Climate stopped working

### ISSUE THREAD

**Issue by mgrefsrud** [Anonym-tsk/home-assistant-components#11]
I have understood that from 0.89 of HA the custom components needs to be structured different or has to contain moe files? At least from my exprience the custom component Xiaomi IR Climate wihich i am very happy that you have built, stopped working. Is there a need to do changes to the component, or is it just me who does not understand what to do?

**Comment by thundergreen** [comment]
There was an update but however i get this error:


```
Error loading custom_components.climate.cozytouch. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/hass/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hass/.homeassistant/custom_components/climate/cozytouch.py", line 8, in <module>
    from homeassistant.components.climate import ClimateDevice, SUPPORT_TARGET_TEMPERATURE_HIGH, \
ImportError: cannot import name 'SUPPORT_ON_OFF'
```

Do I have to delete the old files? so that everything is stored in custo_components/xiaomi_remote

I also changed the credetial format but also get authentication error.

**Comment by Anonym-tsk** [comment]
What is "cozytouch.py"? :)

**Comment by Anonym-tsk** [comment]
Please update component from github. Remove old one and download new one, keeping folder structure.
