### ISSUE TITLE
Error creating commands file

### ISSUE THREAD

**Issue by romarcis** [Anonym-tsk/home-assistant-components#12]
When I create the commands.yaml file I get this error

**`expected dict for dictionary value @ data['comandi']['off']**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/automation/__init__.py", line 155, in reload_service_handler
    conf = await component.async_prepare_reload()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 272, in async_prepare_reload
    conf_util.async_hass_config_yaml(self.hass)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/config.py", line 318, in async_hass_config_yaml
    return await hass.async_add_executor_job(_load_hass_yaml_config)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/config.py", line 315, in _load_hass_yaml_config
    merge_packages_config(hass, config, core_config.get(CONF_PACKAGES, {}))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/config.py", line 644, in merge_packages_config
    PACKAGES_CONFIG_SCHEMA(packages)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/config_validation.py", line 391, in verify
    return schema(value)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: **expected dict for dictionary value @ data['comandi']['off']**`

**Comment by Anonym-tsk** [comment]
Please provide your commands file and configuration
